# Copyright 2010 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# author: alexto@google.com (Alexis O. Torres)
#
# AppEngine YAML configuration is defined here:
#     http://code.google.com/appengine/docs/python/config/appconfig.html
#
# This version number forces folks to deploy with:
#     appcfg.py -A <desired_app_id> -V <desired_app_version> /path/to/bundle

application: invalid-do-not-change-see-comments
version: invalid-do-not-change-see-comments
runtime: python27
threadsafe: yes
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- deferred: on
- remote_api: on

handlers:

# Bugs
#   Bugs API
#   [POST]; create a new bug
- url: /bugs
  script: bugs.handlers.bugs.create.app
  secure: always
  login: required
#   [GET, PUT]; get/update a bug by id
- url: /bugs/\d+
  script: bugs.handlers.bugs.access.app
  secure: always
  login: required
#   [GET]; retrieve a list of bugs
- url: /bugs/all
  script: bugs.handlers.bugs.all.app
  secure: always
  login: required
#   [GET]: retrieve a list of bugs by url
- url: /bugs/url
  script: bugs.handlers.bugs.url.app
  secure: always
  login: required

# Test cycles.
- url: /cycles
  script: handlers.test_cycles.app
  login: required

- url: /cycles/all
  script: handlers.test_cycles.app
  login: required

# Testers.
- url: /testers
  script: handlers.testers.app
  login: required

- url: /testers/all
  script: handlers.testers.app
  login: required

- url: /cycle/\w+/testers
  script: handlers.testers.app
  login: required

- url: /cycle/\w+/testers/all
  script: handlers.testers.app
  login: required
  
# Screenshots URLs.
- url: /screenshots/upload
  script: handlers.screenshots.app
  login: required

- url: /screenshots/fetch
  script: handlers.screenshots.app
  login: required

- url: /screenshots/search
  script: handlers.screenshots.app
  login: required

  
# User facing pages.
- url: /
  script: handlers.home.app
  login: required

# Login utility urls.
- url: /check_login_status
  script: handlers.login_handler.app
  login: required

- url: /check_gdata_login_status
  script: handlers.login_handler.app
  login: required

- url: /gdata_session_token_saver
  script: handlers.login_handler.app
  login: required

# Bug admin.
- url: /admin/bugs
  script: handlers.bugs_admin.app
  login: admin

# Bug fetching.
- url: /get_bugs_for_url
  script: handlers.get_bugs.app
  login: required

- url: /provider/\w+/project/\w+/bugs/\w+
  script: handlers.get_bugs.app
  login: required

- url: /automateRpf
  script: handlers.home_handler.app
  login: required

# Bug reporting.
- url: /bugs/new
  script: handlers.report_bug.app
  login: required

- url: /bugs/update
  script: handlers.report_bug.app
  login: required

- url: /bugs/update_status
  script: handlers.report_bug.app
  login: required

- url: /bugs/update_binding
  script: handlers.report_bug.app
  login: required

- url: /bugs/update_recording
  script: handlers.report_bug.app
  login: required

# Projects handlers
- url: /project/.*
  script: handlers.project_handler.app
  login: required

# Test Suite, Run, Results handlers
- url: /suite/.*
  script: handlers.suite_handler.app

- url: /run/.*
  script: handlers.run_handler.app

- url: /result/.*
  script: handlers.result_handler.app

- url: /tests/.*
  script: handlers.test_handler.app

- url: /testing/.*
  script: handlers.testing_handler.app

- url: /event/.*
  script: handlers.event_handler.app

- url: /home.*
  script: handlers.home_handler.app

# Bug Template handlers
- url: /get_templates
  script: handlers.template_handler.app
  login: required

- url: /new_template
  script: handlers.template_handler.app
  login: required
  

# Static content.
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /extjs
  static_dir: third_party/extjs

- url: /hud/scripts
  static_dir: hud/scripts

- url: /bin
  static_dir: bin

- url: /imgs
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

# Storage handlers
- url: /storage.*
  script: handlers.storage_handler.app


# Crawler tasks URLs.
- url: /tasks/crawl/issuetracker/.*
  script: crawlers.issuetracker_crawler.app
  login: admin

# eReporter.
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?queue\.yaml
- ^(.*/)?cron\.yaml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.old
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*test\.py
- ^(.*/)?.*est_helper\.py
- ^(.*/)?PRESUBMIT\.py
- ^(.*/)?README
- ^(.*/)?OWNERS
- ^(.*/)?BUILD
- ^(.*/)?.*\.bak$

inbound_services:
- warmup
